name: Automate Deploy to Amazon EC2 using Github actions

on:
  push:
    branches: [ master ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Checkout to repo
        uses: actions/checkout@v2
     